/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateFacultyArgs } from "./CreateFacultyArgs";
import { UpdateFacultyArgs } from "./UpdateFacultyArgs";
import { DeleteFacultyArgs } from "./DeleteFacultyArgs";
import { FacultyCountArgs } from "./FacultyCountArgs";
import { FacultyFindManyArgs } from "./FacultyFindManyArgs";
import { FacultyFindUniqueArgs } from "./FacultyFindUniqueArgs";
import { Faculty } from "./Faculty";
import { CourseFindManyArgs } from "../../course/base/CourseFindManyArgs";
import { Course } from "../../course/base/Course";
import { Department } from "../../department/base/Department";
import { FacultyService } from "../faculty.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Faculty)
export class FacultyResolverBase {
  constructor(
    protected readonly service: FacultyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Faculty",
    action: "read",
    possession: "any",
  })
  async _facultiesMeta(
    @graphql.Args() args: FacultyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Faculty])
  @nestAccessControl.UseRoles({
    resource: "Faculty",
    action: "read",
    possession: "any",
  })
  async faculties(
    @graphql.Args() args: FacultyFindManyArgs
  ): Promise<Faculty[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Faculty, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Faculty",
    action: "read",
    possession: "own",
  })
  async faculty(
    @graphql.Args() args: FacultyFindUniqueArgs
  ): Promise<Faculty | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Faculty)
  @nestAccessControl.UseRoles({
    resource: "Faculty",
    action: "create",
    possession: "any",
  })
  async createFaculty(
    @graphql.Args() args: CreateFacultyArgs
  ): Promise<Faculty> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        department: {
          connect: args.data.department,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Faculty)
  @nestAccessControl.UseRoles({
    resource: "Faculty",
    action: "update",
    possession: "any",
  })
  async updateFaculty(
    @graphql.Args() args: UpdateFacultyArgs
  ): Promise<Faculty | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          department: {
            connect: args.data.department,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Faculty)
  @nestAccessControl.UseRoles({
    resource: "Faculty",
    action: "delete",
    possession: "any",
  })
  async deleteFaculty(
    @graphql.Args() args: DeleteFacultyArgs
  ): Promise<Faculty | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Course], { name: "courses" })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  async resolveFieldCourses(
    @graphql.Parent() parent: Faculty,
    @graphql.Args() args: CourseFindManyArgs
  ): Promise<Course[]> {
    const results = await this.service.findCourses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Department, {
    nullable: true,
    name: "department",
  })
  @nestAccessControl.UseRoles({
    resource: "Department",
    action: "read",
    possession: "any",
  })
  async resolveFieldDepartment(
    @graphql.Parent() parent: Faculty
  ): Promise<Department | null> {
    const result = await this.service.getDepartment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
