/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CourseService } from "../course.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CourseCreateInput } from "./CourseCreateInput";
import { CourseWhereInput } from "./CourseWhereInput";
import { CourseWhereUniqueInput } from "./CourseWhereUniqueInput";
import { CourseFindManyArgs } from "./CourseFindManyArgs";
import { CourseUpdateInput } from "./CourseUpdateInput";
import { Course } from "./Course";
import { AdmissionBatchFindManyArgs } from "../../admissionBatch/base/AdmissionBatchFindManyArgs";
import { AdmissionBatch } from "../../admissionBatch/base/AdmissionBatch";
import { AdmissionBatchWhereUniqueInput } from "../../admissionBatch/base/AdmissionBatchWhereUniqueInput";
import { AdmissionCriterionFindManyArgs } from "../../admissionCriterion/base/AdmissionCriterionFindManyArgs";
import { AdmissionCriterion } from "../../admissionCriterion/base/AdmissionCriterion";
import { AdmissionCriterionWhereUniqueInput } from "../../admissionCriterion/base/AdmissionCriterionWhereUniqueInput";
import { AdmissionFormFindManyArgs } from "../../admissionForm/base/AdmissionFormFindManyArgs";
import { AdmissionForm } from "../../admissionForm/base/AdmissionForm";
import { AdmissionFormWhereUniqueInput } from "../../admissionForm/base/AdmissionFormWhereUniqueInput";
import { MarkSheetFindManyArgs } from "../../markSheet/base/MarkSheetFindManyArgs";
import { MarkSheet } from "../../markSheet/base/MarkSheet";
import { MarkSheetWhereUniqueInput } from "../../markSheet/base/MarkSheetWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CourseControllerBase {
  constructor(
    protected readonly service: CourseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Course })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: CourseCreateInput): Promise<Course> {
    return await this.service.create({
      data: {
        ...data,

        department: {
          connect: data.department,
        },

        faculty: data.faculty
          ? {
              connect: data.faculty,
            }
          : undefined,

        university: {
          connect: data.university,
        },
      },
      select: {
        comment: true,
        createdAt: true,
        credits: true,

        department: {
          select: {
            id: true,
          },
        },

        description: true,

        faculty: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,

        university: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Course] })
  @ApiNestedQuery(CourseFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Course[]> {
    const args = plainToClass(CourseFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        comment: true,
        createdAt: true,
        credits: true,

        department: {
          select: {
            id: true,
          },
        },

        description: true,

        faculty: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,

        university: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<Course | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        comment: true,
        createdAt: true,
        credits: true,

        department: {
          select: {
            id: true,
          },
        },

        description: true,

        faculty: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,

        university: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() data: CourseUpdateInput
  ): Promise<Course | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          department: {
            connect: data.department,
          },

          faculty: data.faculty
            ? {
                connect: data.faculty,
              }
            : undefined,

          university: {
            connect: data.university,
          },
        },
        select: {
          comment: true,
          createdAt: true,
          credits: true,

          department: {
            select: {
              id: true,
            },
          },

          description: true,

          faculty: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,

          university: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Course })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<Course | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          comment: true,
          createdAt: true,
          credits: true,

          department: {
            select: {
              id: true,
            },
          },

          description: true,

          faculty: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,

          university: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/admissionBatches")
  @ApiNestedQuery(AdmissionBatchFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AdmissionBatch",
    action: "read",
    possession: "any",
  })
  async findManyAdmissionBatches(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<AdmissionBatch[]> {
    const query = plainToClass(AdmissionBatchFindManyArgs, request.query);
    const results = await this.service.findAdmissionBatches(params.id, {
      ...query,
      select: {
        createdAt: true,
        endDate: true,
        id: true,
        name: true,
        startDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/admissionBatches")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectAdmissionBatches(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionBatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionBatches: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/admissionBatches")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateAdmissionBatches(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionBatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionBatches: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/admissionBatches")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectAdmissionBatches(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionBatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionBatches: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/admissionCriteria")
  @ApiNestedQuery(AdmissionCriterionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AdmissionCriterion",
    action: "read",
    possession: "any",
  })
  async findManyAdmissionCriteria(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<AdmissionCriterion[]> {
    const query = plainToClass(AdmissionCriterionFindManyArgs, request.query);
    const results = await this.service.findAdmissionCriteria(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        minimumMarks: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/admissionCriteria")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectAdmissionCriteria(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionCriterionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionCriteria: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/admissionCriteria")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateAdmissionCriteria(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionCriterionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionCriteria: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/admissionCriteria")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectAdmissionCriteria(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionCriterionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionCriteria: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/admissionForm")
  @ApiNestedQuery(AdmissionFormFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AdmissionForm",
    action: "read",
    possession: "any",
  })
  async findManyAdmissionForm(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<AdmissionForm[]> {
    const query = plainToClass(AdmissionFormFindManyArgs, request.query);
    const results = await this.service.findAdmissionForm(params.id, {
      ...query,
      select: {
        admissionBatch: {
          select: {
            id: true,
          },
        },

        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        formSubmittedAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/admissionForm")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectAdmissionForm(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionFormWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionForm: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/admissionForm")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateAdmissionForm(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionFormWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionForm: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/admissionForm")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectAdmissionForm(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: AdmissionFormWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      admissionForm: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/markSheet")
  @ApiNestedQuery(MarkSheetFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MarkSheet",
    action: "read",
    possession: "any",
  })
  async findManyMarkSheet(
    @common.Req() request: Request,
    @common.Param() params: CourseWhereUniqueInput
  ): Promise<MarkSheet[]> {
    const query = plainToClass(MarkSheetFindManyArgs, request.query);
    const results = await this.service.findMarkSheet(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        marksObtained: true,

        student: {
          select: {
            id: true,
          },
        },

        totalMarks: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/markSheet")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async connectMarkSheet(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: MarkSheetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      markSheet: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/markSheet")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async updateMarkSheet(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: MarkSheetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      markSheet: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/markSheet")
  @nestAccessControl.UseRoles({
    resource: "Course",
    action: "update",
    possession: "any",
  })
  async disconnectMarkSheet(
    @common.Param() params: CourseWhereUniqueInput,
    @common.Body() body: MarkSheetWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      markSheet: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
