/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdmissionBatch } from "../../admissionBatch/base/AdmissionBatch";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsInt,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { AdmissionCriterion } from "../../admissionCriterion/base/AdmissionCriterion";
import { AdmissionForm } from "../../admissionForm/base/AdmissionForm";
import { Department } from "../../department/base/Department";
import { Faculty } from "../../faculty/base/Faculty";
import { MarkSheet } from "../../markSheet/base/MarkSheet";
import { University } from "../../university/base/University";

@ObjectType()
class Course {
  @ApiProperty({
    required: true,
    type: () => [AdmissionBatch],
  })
  @ValidateNested()
  @Type(() => AdmissionBatch)
  @IsOptional()
  admissionBatches?: Array<AdmissionBatch>;

  @ApiProperty({
    required: false,
    type: () => [AdmissionCriterion],
  })
  @ValidateNested()
  @Type(() => AdmissionCriterion)
  @IsOptional()
  admissionCriteria?: Array<AdmissionCriterion>;

  @ApiProperty({
    required: false,
    type: () => [AdmissionForm],
  })
  @ValidateNested()
  @Type(() => AdmissionForm)
  @IsOptional()
  admissionForm?: Array<AdmissionForm>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  credits!: number;

  @ApiProperty({
    required: true,
    type: () => Department,
  })
  @ValidateNested()
  @Type(() => Department)
  department?: Department;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: () => Faculty,
  })
  @ValidateNested()
  @Type(() => Faculty)
  @IsOptional()
  faculty?: Faculty | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: () => [MarkSheet],
  })
  @ValidateNested()
  @Type(() => MarkSheet)
  @IsOptional()
  markSheet?: Array<MarkSheet>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: () => University,
  })
  @ValidateNested()
  @Type(() => University)
  university?: University;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Course as Course };
