/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdmissionBatchUpdateManyWithoutCoursesInput } from "./AdmissionBatchUpdateManyWithoutCoursesInput";
import { ValidateNested, IsOptional, IsInt, IsString } from "class-validator";
import { Type } from "class-transformer";
import { AdmissionCriterionUpdateManyWithoutCoursesInput } from "./AdmissionCriterionUpdateManyWithoutCoursesInput";
import { AdmissionFormUpdateManyWithoutCoursesInput } from "./AdmissionFormUpdateManyWithoutCoursesInput";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { FacultyWhereUniqueInput } from "../../faculty/base/FacultyWhereUniqueInput";
import { MarkSheetUpdateManyWithoutCoursesInput } from "./MarkSheetUpdateManyWithoutCoursesInput";
import { UniversityWhereUniqueInput } from "../../university/base/UniversityWhereUniqueInput";

@InputType()
class CourseUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AdmissionBatchUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => AdmissionBatchUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => AdmissionBatchUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  admissionBatches?: AdmissionBatchUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => AdmissionCriterionUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => AdmissionCriterionUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => AdmissionCriterionUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  admissionCriteria?: AdmissionCriterionUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => AdmissionFormUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => AdmissionFormUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => AdmissionFormUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  admissionForm?: AdmissionFormUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  credits?: number;

  @ApiProperty({
    required: false,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @IsOptional()
  @Field(() => DepartmentWhereUniqueInput, {
    nullable: true,
  })
  department?: DepartmentWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => FacultyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FacultyWhereUniqueInput)
  @IsOptional()
  @Field(() => FacultyWhereUniqueInput, {
    nullable: true,
  })
  faculty?: FacultyWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => MarkSheetUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => MarkSheetUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => MarkSheetUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  markSheet?: MarkSheetUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => UniversityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UniversityWhereUniqueInput)
  @IsOptional()
  @Field(() => UniversityWhereUniqueInput, {
    nullable: true,
  })
  university?: UniversityWhereUniqueInput;
}

export { CourseUpdateInput as CourseUpdateInput };
