/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AdmissionFormService } from "../admissionForm.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AdmissionFormCreateInput } from "./AdmissionFormCreateInput";
import { AdmissionFormWhereInput } from "./AdmissionFormWhereInput";
import { AdmissionFormWhereUniqueInput } from "./AdmissionFormWhereUniqueInput";
import { AdmissionFormFindManyArgs } from "./AdmissionFormFindManyArgs";
import { AdmissionFormUpdateInput } from "./AdmissionFormUpdateInput";
import { AdmissionForm } from "./AdmissionForm";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AdmissionFormControllerBase {
  constructor(
    protected readonly service: AdmissionFormService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AdmissionForm })
  @nestAccessControl.UseRoles({
    resource: "AdmissionForm",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: AdmissionFormCreateInput
  ): Promise<AdmissionForm> {
    return await this.service.create({
      data: {
        ...data,

        admissionBatch: {
          connect: data.admissionBatch,
        },

        course: {
          connect: data.course,
        },

        student: {
          connect: data.student,
        },
      },
      select: {
        admissionBatch: {
          select: {
            id: true,
          },
        },

        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        formSubmittedAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AdmissionForm] })
  @ApiNestedQuery(AdmissionFormFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AdmissionForm",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<AdmissionForm[]> {
    const args = plainToClass(AdmissionFormFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        admissionBatch: {
          select: {
            id: true,
          },
        },

        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        formSubmittedAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AdmissionForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdmissionForm",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: AdmissionFormWhereUniqueInput
  ): Promise<AdmissionForm | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        admissionBatch: {
          select: {
            id: true,
          },
        },

        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        formSubmittedAt: true,
        id: true,

        student: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AdmissionForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdmissionForm",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: AdmissionFormWhereUniqueInput,
    @common.Body() data: AdmissionFormUpdateInput
  ): Promise<AdmissionForm | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          admissionBatch: {
            connect: data.admissionBatch,
          },

          course: {
            connect: data.course,
          },

          student: {
            connect: data.student,
          },
        },
        select: {
          admissionBatch: {
            select: {
              id: true,
            },
          },

          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          formSubmittedAt: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AdmissionForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdmissionForm",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: AdmissionFormWhereUniqueInput
  ): Promise<AdmissionForm | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          admissionBatch: {
            select: {
              id: true,
            },
          },

          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          formSubmittedAt: true,
          id: true,

          student: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
