/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MarkSheetService } from "../markSheet.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MarkSheetCreateInput } from "./MarkSheetCreateInput";
import { MarkSheetWhereInput } from "./MarkSheetWhereInput";
import { MarkSheetWhereUniqueInput } from "./MarkSheetWhereUniqueInput";
import { MarkSheetFindManyArgs } from "./MarkSheetFindManyArgs";
import { MarkSheetUpdateInput } from "./MarkSheetUpdateInput";
import { MarkSheet } from "./MarkSheet";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MarkSheetControllerBase {
  constructor(
    protected readonly service: MarkSheetService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MarkSheet })
  @nestAccessControl.UseRoles({
    resource: "MarkSheet",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: MarkSheetCreateInput): Promise<MarkSheet> {
    return await this.service.create({
      data: {
        ...data,

        course: {
          connect: data.course,
        },

        student: {
          connect: data.student,
        },
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        marksObtained: true,

        student: {
          select: {
            id: true,
          },
        },

        totalMarks: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MarkSheet] })
  @ApiNestedQuery(MarkSheetFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MarkSheet",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<MarkSheet[]> {
    const args = plainToClass(MarkSheetFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        marksObtained: true,

        student: {
          select: {
            id: true,
          },
        },

        totalMarks: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MarkSheet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarkSheet",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: MarkSheetWhereUniqueInput
  ): Promise<MarkSheet | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        marksObtained: true,

        student: {
          select: {
            id: true,
          },
        },

        totalMarks: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MarkSheet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarkSheet",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: MarkSheetWhereUniqueInput,
    @common.Body() data: MarkSheetUpdateInput
  ): Promise<MarkSheet | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          course: {
            connect: data.course,
          },

          student: {
            connect: data.student,
          },
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          marksObtained: true,

          student: {
            select: {
              id: true,
            },
          },

          totalMarks: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MarkSheet })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MarkSheet",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: MarkSheetWhereUniqueInput
  ): Promise<MarkSheet | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          marksObtained: true,

          student: {
            select: {
              id: true,
            },
          },

          totalMarks: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
